name: linting, testing, building
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#just a new comment
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules 
        run: npm install 
      - name: build project
        run: npm run build
      - name: lint ts 
        run: npm run lint
        if: always()
      - name: unit test
        run: npm run test:unit
        if: always()        